### ISSUE TITLE
Support cognito id-tokens with at_hash claims

### ISSUE THREAD

**Issue by shughes-uk** [pvizeli/pycognito#20]
For some reason access tokens acquired via boto3 do not have at_hash claims, but when you use id tokens from the hosted ui, they have at_hash claims. To use jose.jwt.decode on these tokens you have to pass in the access_token at the same time as the ID token or it raises an error.

It may seem like a weird use case to use tokens from the hosted UI with the library but there is some stuff the hosted UI can't do (like update user attributes) that it's nice to use pycognito for. It would be nice if this could be resolved, it might be as simple as changing the decode call to always include the access token.

**Comment by marly-chietton** [comment]
+1

It definiyely seems that jwt.decode needs the access_token when "at_hash" claim is included in the claim set 
https://github.com/mpdavis/python-jose/blob/master/jose/jwt.py#L56
https://github.com/mpdavis/python-jose/blob/master/jose/jwt.py#L73

https://github.com/mpdavis/python-jose/blob/cfbb868efffe05352546f064a47e6d90a53bbae0/jose/jwt.py#L87


u.verify_tokens() gives : `msg = "No access_token provided to compare against at_hash claim."`
https://github.com/mpdavis/python-jose/blob/cfbb868efffe05352546f064a47e6d90a53bbae0/jose/jwt.py#L444

**Comment by Thiebosh** [comment]
found a fix to this, so i created a pull request : https://github.com/pvizeli/pycognito/pull/128

Hopefully, it will be quickly merged :)

**Comment by Thiebosh** [comment]
Found another linked issue : the refresh tokens method needed a little method order flip too. Fidex in same pr
