### ISSUE TITLE
python-jose-cryptodome has a critical vulnerability

### ISSUE THREAD

**Issue by nicholastulach** [pvizeli/pycognito#90]
Please consider using a different cryptography library that is currently maintained.

![142068599-83504556-5740-46d4-81a3-c891466a2b6c](https://user-images.githubusercontent.com/2217724/143303098-62cd148e-10c4-4743-bcac-69a4c0362935.png)

**Comment by pvizeli** [comment]
We use python-jose[cryptography]>=3.2.0
